"""
智能验证助手：自动检测模型通道数并使用正确的数据配置

使用方法:
    python smart_val.py --model models/yolo12x.pt
    python smart_val.py --model runs/train/phase3_channelc2f7/weights/best.pt
"""

import argparse
import torch
from pathlib import Path
import subprocess

def detect_model_channels(model_path):
    """检测模型期望的输入通道数"""
    try:
        ckpt = torch.load(model_path, map_location='cpu')
        
        # 方法1: 检查 YAML 配置
        if 'model' in ckpt and hasattr(ckpt['model'], 'yaml'):
            yaml_cfg = ckpt['model'].yaml
            if 'ch' in yaml_cfg:
                return yaml_cfg['ch']
        
        # 方法2: 检查第一层卷积
        if 'model' in ckpt:
            model = ckpt['model']
            for module in model.modules():
                if isinstance(module, torch.nn.Conv2d):
                    return module.in_channels
        
        return None
    except Exception as e:
        print(f"⚠️  Failed to detect channels: {e}")
        return None


def main():
    parser = argparse.ArgumentParser(description="Smart validation with auto channel detection")
    parser.add_argument('--model', type=str, required=True, help='Path to model weights')
    parser.add_argument('--batch', type=int, default=16, help='Batch size')
    parser.add_argument('--device', type=int, default=0, help='GPU device')
    args = parser.parse_args()
    
    model_path = Path(args.model)
    if not model_path.exists():
        print(f"❌ Model not found: {model_path}")
        return
    
    print("=" * 80)
    print("🔍 Smart Validation Assistant")
    print("=" * 80)
    print()
    print(f"Model: {model_path}")
    print()
    
    # 检测通道数
    print("Detecting model input channels...")
    channels = detect_model_channels(model_path)
    
    if channels is None:
        print("⚠️  Failed to detect channels, assuming RGB-only (3 channels)")
        channels = 3
    else:
        print(f"✅ Detected: {channels} channels")
    print()
    
    # 选择数据配置
    if channels == 3:
        print("📋 Using RGB-only configuration")
        data_cfg = "data/visdrone-rgb-only.yaml"
        val_script = "val_rgb_only.sh"
    elif channels == 4:
        print("📋 Using RGB-D configuration")
        data_cfg = "data/visdrone-rgbd.yaml"
        val_script = "val_depth.sh"
    else:
        print(f"⚠️  Unknown channel count: {channels}")
        print("   Using RGB-only as fallback")
        data_cfg = "data/visdrone-rgb-only.yaml"
        val_script = "val_rgb_only.sh"
    
    print(f"Data config: {data_cfg}")
    print(f"Val script:  {val_script}")
    print()
    
    # 检查配置文件是否存在
    if not Path(data_cfg).exists():
        print(f"❌ Data config not found: {data_cfg}")
        if channels == 3:
            print("\n💡 Creating RGB-only config...")
            create_rgb_only_config()
    
    # 运行验证
    print("=" * 80)
    print("Starting validation...")
    print("=" * 80)
    print()
    
    cmd = [
        "bash", val_script,
        str(model_path),
        data_cfg,
        str(args.batch),
        "640",
        str(args.device)
    ]
    
    subprocess.run(cmd)


def create_rgb_only_config():
    """创建 RGB-only 数据配置"""
    config_content = """# VisDrone Dataset Configuration (RGB-only, no depth)
# Auto-generated by smart_val.py

path: /data2/user/2024/lzy/Datasets/VisDrone2019-DET-YOLO/VisDrone2YOLO/VisDrone2019-DET-val

train: images/rgb
val: images/rgb

names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor

nc: 10

visdrone_mode: true
small_thresh: 1024
medium_thresh: 9216
"""
    
    with open("data/visdrone-rgb-only.yaml", "w") as f:
        f.write(config_content)
    
    print("✅ Created data/visdrone-rgb-only.yaml")


if __name__ == "__main__":
    main()
